name: test_accurate
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  decimal: ^2.3.3
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_flavorizr: ^2.2.3
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.3
  injectable: ^2.3.2
  intl: 0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  nil: ^1.1.1
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  url_launcher: ^6.2.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flavorizr:
  app:
    android:
      flavorDimensions: flavor-type
  flavors:
    prod:
      app:
        name: Test Accurate App
      android:
        applicationId: id.mis.mobile
      ios:
        bundleId: id.mis.mobile
    dev:
      app:
        name: Dev-Test Accurate App
      android:
        applicationId: id.mis.mobilestaging
      ios:
        bundleId: id.mis.mobilestaging
flutter:
  uses-material-design: true
